### ISSUE TITLE
Error in CompileNetwork - unknown function 'warn'

### ISSUE THREAD

**Issue by mbedward** [ralmond/RNetica#21]
Hi - thanks very much for the package.

Attempting to compile a network where one or more nodes do not have explicit CPTs set, i.e. allowing default uniform CPTs, results in an R error following the Netica warning...

```
Netica warning  @276f2f30.
Netica warning: In function CompileNet_bn: some node(s) (e.g. severity) don't have conditional probability tables (CPTs) (they will be taken as having uniform probabilities)
Error in warn(e) : could not find function "warn"
```

This appears to come from here...

https://github.com/ralmond/RNetica/blob/master/R/Networks.R#L60

... where I think ```warn(e)``` should be ```warning(e)```

**Comment by ralmond** [comment]
Thanks!  I fixed it an pushed it out to the Master repository.  It should propagate out to r-universe shortly.
